python generate_random_points.py > out/1.txt
python generate_random_points.py > out/2.txt
python generate_random_points.py > out/3.txt
python generate_random_points.py > out/4.txt
python generate_random_points.py > out/5.txt
python generate_random_points.py > out/6.txt
python generate_random_points.py > out/7.txt
python generate_random_points.py > out/8.txt
python generate_random_points.py > out/9.txt
python generate_random_points.py > out/10.txt